name: pha_gui

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel

  - streamlit
  - numpy
  - pandas
  - scipy
  - networkx
  - pyyaml
  - rdkit
  - parmed
  - pyzmq

  - pip:
      - py3Dmol
      - stmol