#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
OpenMM simulation script builder.

This module builds readable Python simulation scripts from an ordered list of
simulation workflow steps.
"""

from pathlib import Path
import textwrap


class OpenMMScriptBuilder:
    """Build readable OpenMM workflow scripts for iPHAsimulator."""

    def __init__(
        self,
        root_dir="../structure_database",
        polymer_names=None,
        number_of_polymers=None,
        run_name="Test",
    ):
        self.root_dir = str(root_dir)
        self.polymer_names = polymer_names or ["P3HB_10"]
        self.number_of_polymers = number_of_polymers or [25]
        self.run_name = run_name
        self.steps = []

    def add_minimization(self):
        self.steps.append(
            {
                "method": "minimize_energy",
            }
        )

    def add_basic_NVT(
        self,
        total_steps=3000,
        temp=300,
        filename="NVT",
        save_restart=False,
        restart_name=None,
    ):
        self.steps.append(
            {
                "method": "basic_NVT",
                "total_steps": total_steps,
                "temp": temp,
                "filename": filename,
                "save_restart": save_restart,
                "restart_name": restart_name,
            }
        )

    def add_basic_NPT(
        self,
        total_steps=3000,
        temp=300,
        pressure=1,
        filename="NPT",
        save_restart=False,
        restart_name=None,
    ):
        self.steps.append(
            {
                "method": "basic_NPT",
                "total_steps": total_steps,
                "temp": temp,
                "pressure": pressure,
                "filename": filename,
                "save_restart": save_restart,
                "restart_name": restart_name,
            }
        )

    def add_anneal_NVT(
        self,
        start_temp=300,
        max_temp=700,
        cycles=5,
        quench_rate=10,
        steps_per_cycle=500000,
        filename="anneal_NVT",
        save_restart=False,
        restart_name=None,
    ):
        self.steps.append(
            {
                "method": "anneal_NVT",
                "start_temp": start_temp,
                "max_temp": max_temp,
                "cycles": cycles,
                "quench_rate": quench_rate,
                "steps_per_cycle": steps_per_cycle,
                "filename": filename,
                "save_restart": save_restart,
                "restart_name": restart_name,
            }
        )

    def add_thermal_ramp(
        self,
        heating=True,
        ensemble="NPT",
        start_temp=300,
        max_temp=700,
        quench_rate=10,
        total_steps=100000,
        pressure=1,
        filename="thermal_ramp",
        save_restart=False,
        restart_name=None,
    ):
        self.steps.append(
            {
                "method": "thermal_ramp",
                "heating": heating,
                "ensemble": ensemble,
                "start_temp": start_temp,
                "max_temp": max_temp,
                "quench_rate": quench_rate,
                "total_steps": total_steps,
                "pressure": pressure,
                "filename": filename,
                "save_restart": save_restart,
                "restart_name": restart_name,
            }
        )

    def remove_step(self, index):
        self.steps.pop(index)

    def move_step_up(self, index):
        if index <= 0:
            return

        self.steps[index - 1], self.steps[index] = (
            self.steps[index],
            self.steps[index - 1],
        )

    def move_step_down(self, index):
        if index >= len(self.steps) - 1:
            return

        self.steps[index + 1], self.steps[index] = (
            self.steps[index],
            self.steps[index + 1],
        )

    def clear(self):
        self.steps = []

    def get_workflow_summary(self):
        return list(self.steps)

    def write_script(self, output_script):
        output_script = Path(output_script)

        script_text = self.to_script()

        output_script.parent.mkdir(
            parents=True,
            exist_ok=True,
        )

        with open(output_script, "w") as f:
            f.write(script_text)

        print(f"OpenMM script written to:\n{output_script}")

        return output_script

    def to_script(self):
        step_code = self._build_steps_code()

        script = f'''#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Generated OpenMM simulation script.

Generated by OpenMMScriptBuilder.
"""

from src.iphasimulator.pha_filepath_manager import PHAFileManager
from src.iphasimulator.sw_openmm import GromacsSimulation, AmberSimulation


if __name__ == "__main__":

    paths = PHAFileManager({self.root_dir!r})

    polymer_names = {self.polymer_names!r}
    number_of_polymers = {self.number_of_polymers!r}
    run_name = {self.run_name!r}

    melt_name = paths.get_PHA_melt_name(
        polymer_names,
        number_of_polymers,
    )

    melt_dir = paths.get_PHA_melt_dir(
        polymer_names,
        number_of_polymers,
    )

    topology_file = melt_dir / f"{{melt_name}}.top"
    coordinate_file = melt_dir / f"{{melt_name}}.gro"

    run_dir = paths.create_named_PHA_melt_simulation_run_dir(
        polymer_names,
        number_of_polymers,
        run_name=run_name,
    )

    print("Melt name:", melt_name)
    print("Melt dir:", melt_dir)
    print("Topology file:", topology_file)
    print("Coordinate file:", coordinate_file)
    print("OpenMM output directory:", run_dir)

    if not topology_file.exists():
        raise FileNotFoundError(topology_file)

    if not coordinate_file.exists():
        raise FileNotFoundError(coordinate_file)

    if topology_file.suffix == ".top" and coordinate_file.suffix == ".gro":
        simulation_class = GromacsSimulation

    elif topology_file.suffix == ".prmtop" and coordinate_file.suffix in [".rst7", ".inpcrd"]:
        simulation_class = AmberSimulation

    else:
        raise ValueError(
            "Could not infer simulation type from input file extensions."
        )

    sim = simulation_class(
        paths,
        str(topology_file),
        str(coordinate_file),
        output_dir=str(run_dir),
    )

    print(sim)

{step_code}

    print("Simulation workflow finished.")
    print("Final output directory:", sim.output_dir)

    try:
        sim.graph_state_data(data_file)
    except NameError:
        print("No data file generated for plotting.")
'''

        return script

    def _build_steps_code(self):
        if len(self.steps) == 0:
            return textwrap.indent(
                'print("No simulation steps were added.")',
                "    ",
            )

        lines = []

        has_current_sim = False

        for index, step in enumerate(self.steps, start=1):
            method = step["method"]

            lines.append("")
            lines.append(f'print("Running step {index}: {method}")')

            if method == "minimize_energy":
                lines.append("current_sim = sim.minimize_energy()")
                has_current_sim = True

            else:
                if not has_current_sim:
                    raise ValueError(
                        "First simulation step must currently be minimization."
                    )

                if method == "basic_NVT":
                    lines.extend(
                        self._format_basic_NVT(step)
                    )

                elif method == "basic_NPT":
                    lines.extend(
                        self._format_basic_NPT(step)
                    )

                elif method == "anneal_NVT":
                    lines.extend(
                        self._format_anneal_NVT(step)
                    )

                elif method == "thermal_ramp":
                    lines.extend(
                        self._format_thermal_ramp(step)
                    )

                else:
                    raise ValueError(
                        f"Unknown OpenMM workflow method: {method}"
                    )

        return textwrap.indent(
            "\n".join(lines),
            "    ",
        )

    def _format_basic_NVT(self, step):
        return [
            "current_sim, data_file = sim.basic_NVT(",
            "    current_sim,",
            f"    total_steps={step['total_steps']},",
            f"    temp={step['temp']},",
            f"    filename={step['filename']!r},",
            f"    save_restart={step['save_restart']},",
            f"    restart_name={step['restart_name']!r},",
            ")",
        ]

    def _format_basic_NPT(self, step):
        return [
            "current_sim, data_file = sim.basic_NPT(",
            "    current_sim,",
            f"    total_steps={step['total_steps']},",
            f"    temp={step['temp']},",
            f"    pressure={step['pressure']},",
            f"    filename={step['filename']!r},",
            f"    save_restart={step['save_restart']},",
            f"    restart_name={step['restart_name']!r},",
            ")",
        ]

    def _format_anneal_NVT(self, step):
        return [
            "current_sim, data_file = sim.anneal_NVT(",
            "    current_sim,",
            f"    start_temp={step['start_temp']},",
            f"    max_temp={step['max_temp']},",
            f"    cycles={step['cycles']},",
            f"    quench_rate={step['quench_rate']},",
            f"    steps_per_cycle={step['steps_per_cycle']},",
            f"    filename={step['filename']!r},",
            f"    save_restart={step['save_restart']},",
            f"    restart_name={step['restart_name']!r},",
            ")",
        ]

    def _format_thermal_ramp(self, step):
        return [
            "current_sim, data_file = sim.thermal_ramp(",
            "    current_sim,",
            f"    heating={step['heating']},",
            f"    ensemble={step['ensemble']!r},",
            f"    start_temp={step['start_temp']},",
            f"    max_temp={step['max_temp']},",
            f"    quench_rate={step['quench_rate']},",
            f"    total_steps={step['total_steps']},",
            f"    pressure={step['pressure']},",
            f"    filename={step['filename']!r},",
            f"    save_restart={step['save_restart']},",
            f"    restart_name={step['restart_name']!r},",
            ")",
        ]


if __name__ == "__main__":

    builder = OpenMMScriptBuilder(
        root_dir="../structure_database",
        polymer_names=["P3HB_10"],
        number_of_polymers=[25],
        run_name="Test",
    )

    builder.add_minimization()

    builder.add_basic_NVT(
        total_steps=3000,
        temp=300,
        filename="test_NVT",
    )

    builder.write_script(
        "generated_openmm_test.py"
    )